openapi: '3.0.3'

info:
  description: Medicine Tracker
  version: 0.1.0
  title: Medicine Tracker

servers:
  - url: http://localhost:4000/v0

paths:
  /medicine/{googleID}:
    get:
      description: Show all medicine from customers
      parameters:
      - name: googleID
        in: path
        description: google ID
        required: true
        schema:
          $ref: '#/components/schemas/ID'
      responses:
        200:
          description: Found all of customer's medicine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicineArray'
        404:
          description: Customer not found

    post:
      description: Create new medicine for customer
      parameters:
      - name: googleID
        in: path
        description: google ID
        required: true
        schema:
          $ref: '#/components/schemas/ID'
      requestBody:
        description: New Medicine
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Medicine'
      responses:
        201:
          description: Medicine created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medicine'
        409:
          description: Invalid medicine

  /medicine/delete/{medicineID}:
    delete:
      description: Delete a medicine
      parameters:
      - name: medicineID
        in: path
        description: medicine ID
        required: true
        schema:
          $ref: '#/components/schemas/ID'
      responses:
        200:
          description: Medicine found and deleted
        404:
          description: Medicine not found

  /medicine/update/{medicineID}:
     put:
      description: Update Medicine
      parameters:
      - name: medicineID
        in: path
        description: medicine ID
        required: true
        schema:
          $ref: '#/components/schemas/ID'
      requestBody:
        description: New Medicine info
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Medicine'
      responses:
        201:
          description: Medicine updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medicine'
        409:
          description: Invalid medicine

  /medicine/events/{googleID}:
    get:
      description: Show all medicine from customers
      parameters:
      - name: googleID
        in: path
        description: google ID
        required: true
        schema:
          $ref: '#/components/schemas/ID'
      - name: start
        in: query
        description: Required by fullCalendar
        required: false
        schema:
          type: string
      - name: end
        in: query
        description: Required by fullCalendar
        required: false
        schema:
          type: string
      responses:
        200:
          description: Found all of customer's events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventArray'
        404:
          description: Customer not found


  /customer/{googleID}:
    post:
      description: Create new customer
      parameters:
      - name: googleID
        in: path
        description: google ID
        required: true
        schema:
          $ref: '#/components/schemas/ID'
      responses:
        201:
          description: Customer created or already created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        409:
          description: Invalid customer

  /event/update/{medicineID}/{eventID}:
    put:
      description: Update Event
      parameters:
      - name: eventID
        in: path
        description: event ID
        required: true
        schema:
          $ref: '#/components/schemas/ID'
      - name: medicineID
        in: path
        description: medicine ID
        required: true
        schema:
          $ref: '#/components/schemas/ID'
      requestBody:
        description: Update Event info
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        201:
          description: Updated Event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        409:
          description: Invalid Event
      
components:
  schemas:
    ID:
      type: string

    MedicineArray:
      type: array
      items:
        $ref: '#/components/schemas/Medicine'
  
    EventArray:
      type: array
      items:
        $ref: '#/components/schemas/Event'

    Medicine:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        frequency:
          type: number
        doses: 
          type: number
        totalAmount:
          type: number
        time:
          type: string

    Customer:
      type: object
      properties:
        googleID:
          type: string

    Event:
      type: object
      properties:
        taken:
          type: boolean
    